version: '2'
services:
  zookeeperofm1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ofm-1
    ports:
      - "22888":"2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperofm1:22888:2181;zookeeperofm2:32888:2888;zookeeperofm3:42888:3888
    networks:
      - kafka-ofm

  zookeeperofm2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ofm-2
    ports:
      - "32888":"2888"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperofm1:22888:2181;zookeeperofm2:32888:2888;zookeeperofm3:42888:3888
    networks:
      - kafka-ofm

  zookeeperofm3:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ofm-3
    ports:
      - "42888":"3888"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeperofm1:22888:2181;zookeeperofm2:32888:2888;zookeeperofm3:42888:3888
    networks:
      - kafka-ofm

  kafkaofm1:
    image: confluentinc/cp-kafka:latest
    container_name: broker-ofm-1
    depends_on:
      - zookeeperofm1
      - zookeeperofm2
      - zookeeperofm3
    ports:
      - "19092":"9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperofm1:22181,zookeeperofm2:32181,zookeeperofm3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.17.2.210:19092
    networks:
      - kafka-ofm

  kafkaofm2:
    image: confluentinc/cp-kafka:latest
    container_name: broker-ofm-2
    depends_on:
      - zookeeperofm1
      - zookeeperofm2
      - zookeeperofm3
    ports:
      - "29092":"9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeperofm1:22181,zookeeperofm2:32181,zookeeperofm3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.17.2.210:29092
    networks:
      - kafka-ofm

  kafkaofm3:
    image: confluentinc/cp-kafka:latest
    container_name: broker-ofm-3
    depends_on:
      - zookeeperofm1
      - zookeeperofm2
      - zookeeperofm3
    ports:
      - "39092":"9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeperofm1:22181,zookeeperofm2:32181,zookeeperofm3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.17.2.210:39092
    networks:
      - kafka-ofm
networks:
    kafka-ofm:
      driver: bridge
