version: '2'
services:
  zookeeperofm:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafkaofm:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeperofm
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperofm:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.17.2.210:29092,PLAINTEXT_HOST://10.17.2.210:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1